services:
  - type: web
    name: earth-vision-api
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: APP_NAME
        value: Earth Vision API
      - key: APP_ENV
        value: production
      - key: APP_HOST
        value: 0.0.0.0
      - key: ALLOWED_ORIGINS
        sync: false
      - key: PLANETARY_COMPUTER_STAC_URL
        value: https://planetarycomputer.microsoft.com/api/stac/v1
      - key: SENTINEL_COLLECTION
        value: sentinel-2-l2a
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: openai/gpt-oss-20b
