"use client";

import { CalendarDays, Download, Eye, RefreshCcw, Satellite as SatelliteIcon } from "lucide-react";
import { WorkspaceChatRail } from "@/components/workspace-chat-rail";
import { useGarudaStore } from "@/store/use-garuda-store";

export default function SatellitePage() {
  const sentinel = useGarudaStore((state) => state.sentinel);
  const downloadUrl = sentinel?.after_preview_url ?? sentinel?.before_preview_url;
  return <div className="flex min-h-[calc(100vh-72px)] flex-col lg:flex-row"><WorkspaceChatRail /><section className="min-w-0 flex-1 bg-[#0b0e12] p-6 lg:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-xs text-purple-300"><SatelliteIcon className="h-4 w-4" /> Satellite data</div><h1 className="mt-2 text-2xl font-semibold">Satellite scene evidence</h1><p className="mt-1 text-xs text-slate-600">Inspect the selected scenes. Change highlights are available after a completed analysis in Analytics.</p></div><div className="flex gap-2"><a href={downloadUrl ?? undefined} download="earth-vision-satellite-preview.jpg" aria-disabled={!downloadUrl} className="rounded-xl border border-white/10 p-3 text-slate-400 aria-disabled:pointer-events-none aria-disabled:opacity-40" title="Download preview"><Download className="h-4 w-4" /></a><button type="button" onClick={() => window.location.reload()} className="rounded-xl border border-white/10 p-3 text-slate-400" title="Refresh imagery" aria-label="Refresh imagery"><RefreshCcw className="h-4 w-4" /></button></div></div><div className="mt-6 flex items-center gap-4 rounded-2xl border border-white/10 bg-[#101318] px-5 py-4 text-xs text-slate-500"><CalendarDays className="h-4 w-4" />{sentinel ? <><span>Before {sentinel.before_acquired}</span><span>→</span><span>After {sentinel.after_acquired}</span></> : <span>Run an analysis to load scene dates and previews.</span>}<span className="ml-auto flex items-center gap-2 text-emerald-400"><Eye className="h-4 w-4" /> Preview mode</span></div><div className="mt-4 grid gap-4 lg:grid-cols-2">{[["Before", sentinel?.before_preview_url], ["After", sentinel?.after_preview_url]].map(([label, url]) => <div key={label} className="overflow-hidden rounded-2xl border border-white/10 bg-[#101318]"><div className="flex items-center justify-between border-b border-white/10 px-4 py-3 text-xs"><span>{label} scene</span><span className="text-slate-600">Sentinel-2 L2A</span></div>{url ? <img src={url} alt={`${label} satellite preview`} className="h-64 w-full object-cover" /> : <div className="map-surface flex h-64 items-center justify-center text-xs text-slate-500">No scene loaded yet</div>}</div>)}</div></section></div>;
}
